package test.model;

import org.joda.time.DateTime;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.id
     *
     * @mbggenerated Sun Mar 22 01:24:08 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.number
     *
     * @mbggenerated Sun Mar 22 01:24:08 CST 2015
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.name
     *
     * @mbggenerated Sun Mar 22 01:24:08 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.deleted
     *
     * @mbggenerated Sun Mar 22 01:24:08 CST 2015
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.dateCreated
     *
     * @mbggenerated Sun Mar 22 01:24:08 CST 2015
     */
    private DateTime dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.dateModified
     *
     * @mbggenerated Sun Mar 22 01:24:08 CST 2015
     */
    private DateTime dateModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.id
     *
     * @return the value of t_account.id
     *
     * @mbggenerated Sun Mar 22 01:24:08 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.id
     *
     * @param id the value for t_account.id
     *
     * @mbggenerated Sun Mar 22 01:24:08 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.number
     *
     * @return the value of t_account.number
     *
     * @mbggenerated Sun Mar 22 01:24:08 CST 2015
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.number
     *
     * @param number the value for t_account.number
     *
     * @mbggenerated Sun Mar 22 01:24:08 CST 2015
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.name
     *
     * @return the value of t_account.name
     *
     * @mbggenerated Sun Mar 22 01:24:08 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.name
     *
     * @param name the value for t_account.name
     *
     * @mbggenerated Sun Mar 22 01:24:08 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.deleted
     *
     * @return the value of t_account.deleted
     *
     * @mbggenerated Sun Mar 22 01:24:08 CST 2015
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.deleted
     *
     * @param deleted the value for t_account.deleted
     *
     * @mbggenerated Sun Mar 22 01:24:08 CST 2015
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.dateCreated
     *
     * @return the value of t_account.dateCreated
     *
     * @mbggenerated Sun Mar 22 01:24:08 CST 2015
     */
    public DateTime getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.dateCreated
     *
     * @param dateCreated the value for t_account.dateCreated
     *
     * @mbggenerated Sun Mar 22 01:24:08 CST 2015
     */
    public void setDateCreated(DateTime dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.dateModified
     *
     * @return the value of t_account.dateModified
     *
     * @mbggenerated Sun Mar 22 01:24:08 CST 2015
     */
    public DateTime getDateModified() {
        return dateModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.dateModified
     *
     * @param dateModified the value for t_account.dateModified
     *
     * @mbggenerated Sun Mar 22 01:24:08 CST 2015
     */
    public void setDateModified(DateTime dateModified) {
        this.dateModified = dateModified;
    }
}